packaging_format = 2

id = "lutim"
name = "Lutim"
description.en = "Anonymous image hosting service"
description.fr = "Service d'hébergement anonyme d'images"

version = "0.17.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://lut.im"
demo = "https://lut.im/"
userdoc = "https://framagit.org/luc/lutim/wikis/home"
code = "https://framagit.org/fiat-tux/hat-softwares/lutim"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/lutim"

    [install.init_main_permission]
    help.en = "If you set Lutim as visitors, everyone will be able to upload images and share them.<br>But even if not public, everyone can see an image from a link shared with your Lutim."
    help.fr = "Si vous définissez Lutim comme visitors, tout le monde pourra télécharger des images et les partager.<br>Mais même si ce n'est pas public, tout le monde peut voir une image à partir d'un lien partagé avec votre Lutim."
    type = "group"
    default = "visitors"

    [install.always_encrypt]
    ask.en = "Force the encryption of images?"
    ask.fr = "Forcer le chiffrement des images ?"
    type = "boolean"
    default = true

[resources]
        [resources.sources.main]
        url = "https://objects.githubusercontent.com/github-production-release-asset-2e65be/931010077/a016684f-42e4-4b0b-b93e-cc56a8b4615f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250214%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250214T233511Z&X-Amz-Expires=300&X-Amz-Signature=a2dbfc081322f990fb8c9941790143b1e3a633211e3470d08ccbf43101edf191&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dblahaj.pics.tar.gz&response-content-type=application%2Foctet-stream"
        sha256 = "11096b8723bbd80e9cf97d4f6381f30332a278b1c0b24bea54b7c15f2070a0cd"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "carton perlmagick libpq-dev shared-mime-info"
